# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee8ffcec0931df8b88305b58d7815e7465f4c6d24f2da18adca782147c0ba9e11513c18a9e5c650a94faee09ec69d5ec51d5b69c0b4a15c7852c97c7c1cdc92c

test:
  secret_key_base: 3cf2f649596a9fcc514daba3c087431071cfbf41b24d1f5ea1c4a8277803a0c21653ec060252e48be6beb5a188d59c51712910913a5c0cdba65dcc3a61674b24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
